output messages in stderr.

diff --git a/config/bashrc b/config/bashrc
--- a/config/bashrc
+++ b/config/bashrc
@@ -5,7 +5,7 @@
 if [[ -f "${HOME}/.posixShellRC" ]]; then
     source "$HOME/.posixShellRC"
 else
-    echo "[posix shell rc] not found!"
+    echo "[posix shell rc] not found!" >&2
 fi
 
 # tab title {{{
