update bash prompt;
also change the word color in bash prompt.
show the git information.

diff --git a/config/bashrc_file b/config/bashrc_file
--- a/config/bashrc_file
+++ b/config/bashrc_file
@@ -10,13 +10,37 @@ fi
 
 ##{{{ prompt
 # useful: https://qiita.com/hmmrjn/items/60d2a64c9e5bf7c0fe60
+# path
 export PS1='\[\e[46m\]\w\[\e[0m\]\n'
 if [[ ${SSH_CLIENT} == "" ]]; then
+    # time
     export PS1=$PS1'\[\e[32m\]\t\[\e[0m\]'
 else
+    # host name
     export PS1=$PS1'\[\e[36m\]${HOSTNAME%%.*}\[\e[0m\]'
 fi
-export PS1=$PS1' \[\e[1m\e[31m\]\u\[\e[0m\] \$ '
+# user name (bold)
+export PS1=$PS1' \[\e[1m\e[31m\]\u\[\e[0m\]'
+
+# git information
+GITPROMPT=${HOME}/.bash/git-prompt.sh
+if [[ -f $GITPROMPT ]]; then
+    # unstaged (*) and staged (+) are shown
+    export GIT_PS1_SHOWDIRTYSTATE=1
+    source $GITPROMPT
+    export PS1=$PS1' $(__git_ps1 "(%s)")'
+fi
+
+# change red if the previous command was failed.
+# https://qiita.com/rtakasuke/items/4b50e156ab82b0824676
+export PS1=$PS1" \`
+if [ \$? = 0 ]; then
+    echo '\$';
+else
+    echo \[\e[31m\]??\[\e[0m\];
+fi
+ \` "
+
 # }}}
 
 ##{{{ key bind
